service: serverless-lambda-typescript-example

provider:
  name: aws
  runtime: nodejs6.10
  stage: demo  
  region: us-east-1

plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  include:
    src/**
  exclude:
    - node_modules/**/*
    - src/**/*.ts

functions:
  getCity:
    handler: src/cities/cities.getCity
    description: Returns a single city.

    environment:
      FAVORITE_CITY: Budapest

    events:
      - http:
          path: cities/{id}
          method: get
          request:
            parameters:
              paths:
                id: true
